image: Visual Studio 2017
configuration: Release

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver

build:
  project: RummeltSoftware.GELF.sln

artifacts:
  - path: '**\*.nupkg'